id: P010649
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18760
  title: མདོ་ཁམས་འབྲོག་པའི་ཁེད།
  author: ''
  volumes:
    f12bcdbf95df409d99fa5d9e90a63696:
      image_group_id: I8LS18762
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
